const posts = [
  {
    id: 1,
    title: "AI Transforming Patient Diagnosis",
    image: "public/images/ai-healthcare.jpg",
    category: "Technology",
    subcategory: "AI",
    date: "April 25, 2025",
    summary:
      "How AI models are changing the healthcare industry by improving early disease detection.",
    content:
      "Artificial intelligence has greatly enhanced diagnostic accuracy in healthcare. Today’s deep-learning algorithms analyze medical imaging to spot anomalies faster than traditional methods. Integrating patient history and genomic data, these AI systems provide doctors with risk scores and treatment suggestions, reducing time to diagnosis and improving outcomes. Hospitals using AI-driven triage report a 20% drop in misdiagnosis rates, showing the real impact of this technology on patient care.",
    featured: true,
    author: "John Doe",
    trending: true,
  },
  {
    id: 2,
    title: "Building Scalable APIs with Node.js",
    image: "https://source.unsplash.com/featured/?code,api",
    category: "Technology",
    subcategory: "Web Development",
    date: "April 24, 2025",
    summary:
      "Best practices for designing and deploying high-performance RESTful APIs.",
    content:
      "Node.js continues to dominate server-side JavaScript because of its event-driven architecture and npm ecosystem. To build scalable APIs, start by structuring routes with Express or Fastify, implement rate limiting with middleware like express-rate-limit, and use connection pooling for databases. Employ clustering or PM2 to take advantage of multiple CPU cores. Finally, monitor performance using APM tools such as New Relic or Datadog. Following these practices ensures your API can handle spikes in traffic while maintaining low latency.",
    featured: false,
    author: "Emily Carter",
    trending: true,
  },
  {
    id: 3,
    title: "Mastering CSS Grid for Responsive Layouts",
    image: "https://source.unsplash.com/800x600/?css,grid",
    category: "Technology",
    subcategory: "Web Development",
    date: "April 23, 2025",
    summary: "How to leverage CSS Grid to create fluid, adaptive designs.",
    content:
      "CSS Grid revolutionizes layout design by allowing two-dimensional control over rows and columns. Start with defining grid containers and using `grid-template` properties for structure. Employ fractional units (`fr`) for flexible sizing, and media queries to tweak grid templates at breakpoints. Implicit grids and the auto-placement algorithm enable content to flow naturally. Combine CSS Grid with Flexbox for components that need single-axis alignment. This approach drastically reduces dependency on fragile floats or hacks, giving you clean, semantic HTML.",
    featured: false,
    author: "David Kim",
    trending: false,
  },
  {
    id: 4,
    title: "Progressive Web Apps: Bridging Web & Mobile",
    image: "https://source.unsplash.com/800x600/?pwa,web",
    category: "Technology",
    subcategory: "Web Development",
    date: "April 22, 2025",
    summary: "Why PWAs are crucial for offline-first, app-like experiences.",
    content:
      "Progressive Web Apps (PWAs) offer offline functionality via service workers, push notifications, and home-screen installation—without app-store friction. To convert your site, register a service worker that caches essential assets, define a `manifest.json` for installability, and implement background sync for queued requests. PWAs load in under a second on repeat visits, increasing engagement by up to 50%. As browser support solidifies, PWAs will become the default approach for high-performance, cross-platform user experiences.",
    featured: true,
    author: "Sarah Lee",
    trending: false,
  },
  {
    id: 5,
    title: "Containerizing Your App with Docker",
    image: "https://source.unsplash.com/800x600/?docker,container",
    category: "Technology",
    subcategory: "Web Development",
    date: "April 21, 2025",
    summary: "Step-by-step guide to Dockerizing a full-stack application.",
    content:
      "Docker simplifies environment consistency by packaging apps and dependencies into containers. To Dockerize your full-stack project, write a `Dockerfile` for each service (frontend, backend, database), define multi-stage builds to minimize image size, and configure `docker-compose.yml` for orchestration. Use volumes for data persistence, map ports for access, and set health checks. Integrating Docker into CI/CD pipelines ensures every commit is tested in an identical environment, eliminating “it works on my machine” issues.",
    featured: false,
    author: "Alex Johnson",
    trending: false,
  },
  {
    id: 6,
    title: "Cross-Platform Development with Flutter",
    image: "https://source.unsplash.com/800x600/?flutter,mobile",
    category: "Technology",
    subcategory: "Mobile Apps",
    date: "April 20, 2025",
    summary:
      "How Flutter enables natively compiled apps for mobile, web, and desktop.",
    content:
      "Flutter uses Dart to compile to native ARM code, delivering smooth 60fps animations and a unified codebase across iOS, Android, web, and desktop. Widget-based architecture allows for customizable UI and hot reload accelerates development. Integrate with existing apps via Add-to-App, and use packages like `provider` or `bloc` for state management. Performance benchmarks show Flutter apps matching native speed in most real-world scenarios, making it a top choice for startups and enterprises alike.",
    featured: true,
    author: "Nina Patel",
    trending: true,
  },
  {
    id: 7,
    title: "Optimizing React Native Performance",
    image: "https://source.unsplash.com/800x600/?react-native,performance",
    category: "Technology",
    subcategory: "Mobile Apps",
    date: "April 19, 2025",
    summary: "Techniques to keep your React Native app smooth and responsive.",
    content:
      "Start by using `PureComponent` or `React.memo` to prevent unnecessary re-renders, and avoid inline functions in render. Use the Hermes JS engine for faster startup, and leverage `FlatList` with proper `keyExtractor` for long lists. Offload heavy computations to native modules or background threads using `react-native-threads`. Finally, profile your app with Flipper and React DevTools to pinpoint bottlenecks.",
    featured: false,
    author: "Oliver Grant",
    trending: false,
  },
  {
    id: 8,
    title: "Designing for Foldables and Tablets",
    image: "https://source.unsplash.com/800x600/?foldable,tablet",
    category: "Technology",
    subcategory: "Mobile Apps",
    date: "April 18, 2025",
    summary: "Best practices for adaptive layouts on larger, foldable screens.",
    content:
      "Foldable phones and tablets demand responsive designs that adapt to multiple aspect ratios. Use constraint-based layouts in Android and SwiftUI’s adaptive stacks on iOS. Detect hinge regions, handle multi-window mode, and provide dual-screen-specific UI cues. Testing on emulators and real devices is crucial to ensure seamless transitions between folded and unfolded states.",
    featured: false,
    author: "Maya Lopez",
    trending: false,
  },
  {
    id: 9,
    title: "5G-Enhanced AR Experiences on Mobile",
    image: "https://source.unsplash.com/800x600/?5g,augmented-reality",
    category: "Technology",
    subcategory: "Mobile Apps",
    date: "April 17, 2025",
    summary: "Leveraging 5G’s low latency for real-time augmented reality.",
    content:
      "With 5G’s sub-10ms latency, AR apps can stream high-resolution assets and run AI inference on the edge. Implementing WebXR or ARCore/ARKit now supports multi-user shared experiences, making collaborative AR gaming and remote assistance practical. Optimize for bandwidth by using adaptive bitrate streaming and progressive asset loading.",
    featured: true,
    author: "Liam Torres",
    trending: false,
  },
  {
    id: 10,
    title: "Ethical AI: Bias Detection and Mitigation",
    image: "https://source.unsplash.com/800x600/?ethical-ai,bias",
    category: "Technology",
    subcategory: "AI",
    date: "April 16, 2025",
    summary: "Tools and processes to ensure fair and transparent AI models.",
    content:
      "AI bias can arise from unbalanced training data or flawed labeling. Use techniques like SHAP and LIME to explain model decisions, and implement fairness metrics (e.g., demographic parity) during validation. Maintain model cards for documentation, and adopt a human-in-the-loop system for continuous bias monitoring. Regulatory frameworks such as the EU AI Act are pushing for mandatory bias audits in high-risk applications.",
    featured: false,
    author: "Isabella Nguyen",
    trending: false,
  },
  {
    id: 11,
    title: "Edge AI in IoT Devices",
    image: "https://source.unsplash.com/800x600/?edge-ai,iot",
    category: "Technology",
    subcategory: "AI",
    date: "April 15, 2025",
    summary: "Running ML models locally for low-latency, offline intelligence.",
    content:
      "Edge AI pushes inference to devices like cameras and sensors, reducing cloud dependency. Lightweight frameworks such as TensorFlow Lite and ONNX Runtime enable computer vision, keyword spotting, and anomaly detection on microcontrollers and edge gateways. This approach cuts bandwidth usage and improves response times in smart factories and retail analytics.",
    featured: true,
    author: "Daniel Frost",
    trending: false,
  },
  {
    id: 12,
    title: "Gadget Roundup: Smartwatches Compared",
    image: "https://source.unsplash.com/800x600/?smartwatch,fitness",
    category: "Technology",
    subcategory: "Gadgets",
    date: "April 14, 2025",
    summary:
      "Apple Watch vs. Galaxy Watch vs. Fitbit—and which fits your lifestyle.",
    content:
      "We benchmark battery life, health-tracking accuracy, and app ecosystems across top smartwatches. The Apple Watch Series 9 excels in ECG and app variety; Galaxy Watch 6 delivers a vibrant display and seamless Android integration; Fitbit Sense 2 offers stress management and long battery life. Your choice depends on your platform, fitness goals, and budget.",
    featured: false,
    author: "Sophia Adams",
    trending: false,
  },
  {
    id: 13,
    title: "Top 5 Underrated Destinations for 2025",
    image: "https://source.unsplash.com/800x600/?travel,underrated",
    category: "Travel",
    subcategory: "Destinations",
    date: "April 13, 2025",
    summary: "Escape the crowds with these hidden-gem locales.",
    content:
      "Consider Georgia’s Svaneti region for medieval towers, Namibia’s Skeleton Coast for stark beauty, and Bolivia’s Uyuni Salt Flats for otherworldly landscapes. Each offers unique culture, affordable stays, and fewer tourists—perfect for 2025’s off-the-beaten-path seekers.",
    featured: true,
    author: "Elena Russo",
    trending: true,
  },
  {
    id: 14,
    title: "Packing Light: Minimalist Travel Tips",
    image: "https://source.unsplash.com/800x600/?packing,travel",
    category: "Travel",
    subcategory: "Tips",
    date: "April 12, 2025",
    summary: "Master the art of traveling with just a carry-on.",
    content:
      "Choose multi-purpose clothing, use packing cubes, and pack quick-dry fabrics. Weigh your bag beforehand, carry toiletries in TSA-approved containers, and digitize documents. Traveling light reduces costs and stress, letting you focus on experiences, not suitcases.",
    featured: false,
    author: "Olivia Carter",
    trending: false,
  },
  {
    id: 15,
    title: "Epic Hiking Trails to Conquer",
    image: "https://source.unsplash.com/800x600/?hiking,trail",
    category: "Travel",
    subcategory: "Adventures",
    date: "April 11, 2025",
    summary:
      "From Torres del Paine to the Annapurna Circuit—your next big challenge.",
    content:
      "Chile’s W Trek offers dramatic glaciers and wind-swept peaks. Nepal’s Annapurna Circuit blends cultural immersion with Himalayan vistas. Iceland’s Laugavegur Trail stuns with geothermal colors. Prepare with layered gear, navigation tools, and local guides to tackle these iconic routes safely.",
    featured: true,
    author: "Daniel Moore",
    trending: false,
  },
  {
    id: 16,
    title: "Budget Travel: Southeast Asia on $30/Day",
    image: "https://source.unsplash.com/800x600/?southeast-asia,budget",
    category: "Travel",
    subcategory: "Budget Travel",
    date: "April 10, 2025",
    summary: "Stretch your dollars in Thailand, Vietnam, and Cambodia.",
    content:
      "Stay in guesthouses for $10/night, eat street food for $2–3 per meal, use local buses, and book tours directly. With mindful planning, you can experience temples, beaches, and cuisine on a shoestring.",
    featured: false,
    author: "Ava Richardson",
    trending: false,
  },
  {
    id: 17,
    title: "Farm-to-Table Recipes for Spring",
    image: "https://source.unsplash.com/800x600/?farm-to-table,food",
    category: "Food",
    subcategory: "Recipes",
    date: "April 9, 2025",
    summary: "Seasonal dishes featuring fresh, local produce.",
    content:
      "Try asparagus risotto with lemon zest, pea-mint soup, and rhubarb crumble. Prioritize simple techniques that let ingredients shine. Substitute locally grown vegetables for endless flavor variations.",
    featured: true,
    author: "Miguel Pereira",
    trending: true,
  },
  {
    id: 18,
    title: "Top 10 Restaurants in New York City",
    image: "https://source.unsplash.com/800x600/?restaurant,new-york",
    category: "Food",
    subcategory: "Restaurants",
    date: "April 8, 2025",
    summary: "From Michelin-starred fine dining to hidden gems.",
    content:
      "Don’t miss the omakase at Sushi Azabu, the tasting menu at Eleven Madison Park, or the homestyle Italian at L’Artusi. For budget eats, try Xi’an Famous Foods and Vanessa’s Dumpling House.",
    featured: false,
    author: "Noah Sinclair",
    trending: false,
  },
  {
    id: 19,
    title: "Keto-Friendly Desserts That Actually Taste Good",
    image: "https://source.unsplash.com/800x600/?keto,dessert",
    category: "Food",
    subcategory: "Diets",
    date: "April 7, 2025",
    summary: "Low-carb sweets without the sugar crash.",
    content:
      "Recipes include avocado-cocoa mousse sweetened with erythritol, almond-flour lemon bars, and whipped-cream berry parfaits. These treats keep carbs below 5g per serving while delivering real flavor.",
    featured: false,
    author: "Emma Brooks",
    trending: false,
  },
  {
    id: 20,
    title: "Meal Prep Tips for Busy Professionals",
    image: "https://source.unsplash.com/800x600/?meal-prep,food",
    category: "Food",
    subcategory: "Cooking Tips",
    date: "April 6, 2025",
    summary: "Save time and eat well with these weekly strategies.",
    content:
      "Batch-cook grains and proteins, use mason-jar salads, and freeze single-serve portions. Invest in quality containers and plan recipes around overlapping ingredients to minimize waste and streamline your routine.",
    featured: true,
    author: "Lucas Graham",
    trending: false,
  },
  {
    id: 21,
    title: "Declutter Your Home in a Weekend",
    image: "https://source.unsplash.com/800x600/?declutter,home",
    category: "Lifestyle",
    subcategory: "Minimalism",
    date: "April 5, 2025",
    summary: "A step-by-step plan to clear out clutter and simplify.",
    content:
      "Start by sorting by category—clothes, books, kitchen items—then apply the “does it spark joy?” test. Donate or sell unused items, and adopt a one-in, one-out rule to prevent future buildup. Minimalism reduces stress and makes cleaning easier.",
    featured: false,
    author: "Hiroshi Tanaka",
    trending: false,
  },
  {
    id: 22,
    title: "Morning Routines for Peak Productivity",
    image: "https://source.unsplash.com/800x600/?morning,routine",
    category: "Lifestyle",
    subcategory: "Productivity",
    date: "April 4, 2025",
    summary: "Habits to start your day energized and focused.",
    content:
      "Combine meditation, light exercise, and a priority-driven to-do list. Use the Pomodoro Technique during morning deep-work sessions, and limit email first thing to avoid distractions. Consistency amplifies results over weeks.",
    featured: true,
    author: "Emma Brooks",
    trending: false,
  },
  {
    id: 23,
    title: "Home Yoga Practices for Stress Relief",
    image: "https://source.unsplash.com/800x600/?yoga,wellness",
    category: "Lifestyle",
    subcategory: "Wellness",
    date: "April 3, 2025",
    summary: "Simple sequences you can do anywhere, anytime.",
    content:
      "Try sun salutations for energy, seated forward folds for calm, and gentle twists to release tension. Pair your practice with breathing exercises for maximum benefit. No equipment needed—just a mat and quiet space.",
    featured: false,
    author: "Noah Sinclair",
    trending: false,
  },
  {
    id: 24,
    title: "DIY Indoor Herb Garden Ideas",
    image: "https://source.unsplash.com/800x600/?herbgarden,indoor",
    category: "Lifestyle",
    subcategory: "Home",
    date: "April 2, 2025",
    summary: "Grow fresh herbs on your windowsill.",
    content:
      "Use mason jars or small pots, ensure 6+ hours of sunlight, and start with easy herbs like basil, mint, and parsley. Rotate pots, water when topsoil is dry, and trim regularly to encourage bushy growth.",
    featured: true,
    author: "Sofia Ramirez",
    trending: false,
  },
  {
    id: 25,
    title: "2025 Summer Fashion Trends",
    image: "https://source.unsplash.com/800x600/?summer,fashion",
    category: "Fashion",
    subcategory: "Trends",
    date: "April 1, 2025",
    summary: "Bold colors, oversized silhouettes, and sustainable materials.",
    content:
      "Neon shades are making a comeback, paired with relaxed tailoring and recycled fabrics. Look for recycled nylon swimwear, upcycled denim, and statement accessories like chunky chain necklaces.",
    featured: false,
    author: "Harper James",
    trending: false,
  },
  {
    id: 26,
    title: "Building a Capsule Wardrobe",
    image: "https://source.unsplash.com/800x600/?capsule,wardrobe",
    category: "Fashion",
    subcategory: "Sustainable",
    date: "March 31, 2025",
    summary: "Key pieces that last and reduce fashion waste.",
    content:
      "Invest in high-quality basics: a tailored blazer, white tee, dark jeans, and versatile dress. Choose eco-friendly brands that use organic cotton and low-impact dyes. Rotate these staples seasonally to minimize consumption.",
    featured: true,
    author: "Liam Parker",
    trending: false,
  },
  {
    id: 27,
    title: "Accessorizing: From Scarves to Statement Belts",
    image: "https://source.unsplash.com/800x600/?accessories,fashion",
    category: "Fashion",
    subcategory: "Accessories",
    date: "March 30, 2025",
    summary: "Small additions that elevate any outfit.",
    content:
      "Mix delicate gold jewelry with oversized scarves for contrast. Leather belts cinch waists on dresses, and silk bandanas add color to neutral looks. Don’t overlook hats—fedoras and bucket hats are top this season.",
    featured: false,
    author: "Ava Mitchell",
    trending: false,
  },
  {
    id: 28,
    title: "Transitional Pieces for Spring to Summer",
    image: "https://source.unsplash.com/800x600/?spring,summer,fashion",
    category: "Fashion",
    subcategory: "Seasonal",
    date: "March 29, 2025",
    summary: "How to layer light jackets and dresses as temperatures rise.",
    content:
      "Pair lightweight trenches with midi dresses, add loafers instead of boots, and swap tights for bare legs. Neutral palettes with pops of pastel keep the look fresh during seasonal shifts.",
    featured: true,
    author: "Maya Lopez",
    trending: false,
  },
  {
    id: 29,
    title: "Home Workouts for Every Fitness Level",
    image: "https://source.unsplash.com/800x600/?workout,fitness",
    category: "Health",
    subcategory: "Fitness",
    date: "March 28, 2025",
    summary: "Bodyweight routines you can do in your living room.",
    content:
      "Combine squats, push-ups, and planks in tabata intervals. Modify intensity by adjusting rest periods and reps. Add resistance bands for variety. Consistency—30 minutes, 4 times a week—yields strength and cardio gains.",
    featured: false,
    author: "Miles Carter",
    trending: false,
  },
  {
    id: 30,
    title: "Managing Anxiety with Mindfulness",
    image: "https://source.unsplash.com/800x600/?mindfulness,anxiety",
    category: "Health",
    subcategory: "Mental Health",
    date: "March 27, 2025",
    summary: "Techniques to calm your mind and reduce stress.",
    content:
      "Practice the 5-4-3-2-1 grounding exercise, guided breathing, and mindful journaling. Use apps that remind you to pause and observe your thoughts. Over time, these habits can rewire your stress response.",
    featured: true,
    author: "Zara Bennett",
    trending: false,
  },
  {
    id: 31,
    title: "Anti-Inflammatory Nutrition 101",
    image: "https://source.unsplash.com/800x600/?anti-inflammatory,food",
    category: "Health",
    subcategory: "Nutrition",
    date: "March 26, 2025",
    summary: "Foods that help fight chronic inflammation.",
    content:
      "Include berries, leafy greens, turmeric, and fatty fish rich in omega-3s. Avoid processed sugars and refined oils. Incorporate green tea and dark chocolate for antioxidants. Balanced meals with these ingredients support joint health and overall well-being.",
    featured: false,
    author: "Lucas Brown",
    trending: false,
  },
  {
    id: 32,
    title: "Breakthroughs in Telemedicine",
    image: "https://source.unsplash.com/800x600/?telemedicine,healthcare",
    category: "Health",
    subcategory: "Medicine",
    date: "March 25, 2025",
    summary: "How virtual care is reshaping patient access and outcomes.",
    content:
      "Telehealth platforms now integrate remote monitoring, AI triage bots, and e-prescriptions. Studies show virtual visits reduce hospital readmissions by 15%. As broadband access expands, telemedicine will become a standard of care in both urban and rural settings.",
    featured: true,
    author: "Sophie Bennett",
    trending: false,
  },
  {
    id: 33,
    title: "Jamstack: Decoupled Web Architecture",
    image: "https://source.unsplash.com/800x600/?jamstack,web",
    category: "Technology",
    subcategory: "Web Development",
    date: "March 24, 2025",
    summary:
      "Why JAM (JavaScript, APIs, Markup) is accelerating site performance.",
    content:
      "By pre-rendering pages at build time and fetching data via APIs, Jamstack sites achieve sub-second load times and enhanced security. Platforms like Netlify and Vercel automate builds and global CDNs. Use headless CMS (e.g. Contentful) to manage content, and static site generators (e.g. Gatsby, Next.js) to compile your markup.",
    featured: false,
    author: "Ava Mitchell",
    trending: false,
  },
  {
    id: 34,
    title: "Serverless Functions on AWS Lambda",
    image: "https://source.unsplash.com/800x600/?serverless,aws",
    category: "Technology",
    subcategory: "Web Development",
    date: "March 23, 2025",
    summary: "Deploy backend code without managing servers.",
    content:
      "AWS Lambda runs your code in response to events, scaling automatically. Pair with API Gateway for RESTful endpoints, and use IAM roles to secure permissions. Monitor with CloudWatch and optimize cold starts using provisioned concurrency. Ideal for microservices and event-driven tasks.",
    featured: true,
    author: "Daniel Moore",
    trending: false,
  },
  {
    id: 35,
    title: "Micro-Animations with CSS and JS",
    image: "https://source.unsplash.com/800x600/?animation,css",
    category: "Technology",
    subcategory: "Web Development",
    date: "March 22, 2025",
    summary: "Add delight with subtle hover and scroll effects.",
    content:
      "Use CSS `@keyframes` for simple loops, and the Intersection Observer API to trigger animations on scroll. Libraries like GreenSock (GSAP) offer robust timelines and easing functions. Balance performance by limiting heavy animations and using `will-change` sparingly.",
    featured: false,
    author: "Harper James",
    trending: false,
  },
  {
    id: 36,
    title: "Building Chatbots with GPT-4 API",
    image: "https://source.unsplash.com/800x600/?chatbot,ai",
    category: "Technology",
    subcategory: "AI",
    date: "March 21, 2025",
    summary: "Integrate OpenAI’s API to power conversational assistants.",
    content:
      "Leverage GPT-4’s endpoint for user prompts, implement fallback logic for token limits, and fine-tune with domain-specific data. Use streaming responses for live typing effects, and secure your API key with server-side proxies. Chatbots can handle support tickets, scheduling, and FAQ automation.",
    featured: false,
    author: "Miles Carter",
    trending: false,
  },
  {
    id: 37,
    title: "Wearable Health Gadgets in 2025",
    image: "https://source.unsplash.com/800x600/?wearable,health",
    category: "Technology",
    subcategory: "Gadgets",
    date: "March 20, 2025",
    summary:
      "From smart rings to AR glasses—what’s next on your wrist and face.",
    content:
      "Smart rings now track sleep stages and ECG, while AR glasses from major brands are shedding bulk for fashion-friendly form factors. Battery and sensor improvements mean continuous vitals monitoring and hands-free notifications without a phone tether.",
    featured: true,
    author: "Sophia Adams",
    trending: false,
  },
  {
    id: 38,
    title: "Top National Parks to Visit in 2025",
    image: "https://source.unsplash.com/800x600/?national-park,nature",
    category: "Travel",
    subcategory: "Destinations",
    date: "March 19, 2025",
    summary: "Explore the best of nature across continents.",
    content:
      "Consider Canada’s Banff, Australia’s Kakadu, and Tanzania’s Serengeti for wildlife and landscapes. Plan ahead for permits, and visit off-peak seasons to avoid crowds. Each park offers unique ecosystems—from tundra to tropical wetlands.",
    featured: false,
    author: "Hiroshi Tanaka",
    trending: false,
  },
  {
    id: 39,
    title: "How to Find Flight Deals in 2025",
    image: "https://source.unsplash.com/800x600/?flight,travel",
    category: "Travel",
    subcategory: "Tips",
    date: "March 18, 2025",
    summary: "Use tech tools to secure the lowest airfare.",
    content:
      "Set fare alerts on platforms like Skyscanner and Hopper, book 6–8 weeks in advance, and be flexible with dates and nearby airports. Consider budget carriers but watch for baggage fees. Clear cookies or use incognito to avoid dynamic pricing.",
    featured: false,
    author: "Noah Sinclair",
    trending: false,
  },
  {
    id: 40,
    title: "Kayaking Adventures You Can’t Miss",
    image: "https://source.unsplash.com/800x600/?kayaking,adventure",
    category: "Travel",
    subcategory: "Adventures",
    date: "March 17, 2025",
    summary: "From sea caves to river rapids—paddle your way to thrills.",
    content:
      "Explore California’s Channel Islands by kayak, navigate Norway’s fjords, or tackle the Colorado River’s Grand Canyon segment. Always check weather, wear a life vest, and go with certified guides for safety.",
    featured: true,
    author: "Miles Carter",
    trending: false,
  },
  {
    id: 41,
    title: "Cooking for Beginners: 5 Essential Skills",
    image: "https://source.unsplash.com/800x600/?cooking,beginner",
    category: "Food",
    subcategory: "Cooking Tips",
    date: "March 16, 2025",
    summary: "Knife techniques, seasoning, and timing demystified.",
    content:
      "Learn how to julienne and dice vegetables consistently, taste as you cook, master basic sautés and roasts, and understand heat control. These foundational skills build confidence in the kitchen.",
    featured: false,
    author: "Emma Brooks",
    trending: false,
  },
  {
    id: 42,
    title: "Hostel vs. Hotel vs. Airbnb",
    image: "https://source.unsplash.com/800x600/?hostel,airbnb",
    category: "Travel",
    subcategory: "Budget Travel",
    date: "March 15, 2025",
    summary: "Pros and cons of each option for frugal travelers.",
    content:
      "Hostels offer community and low cost; hotels guarantee privacy and services; Airbnb provides local immersion. Compare nightly rates, amenities, and cancellation policies to choose what fits your trip style.",
    featured: false,
    author: "Lucas Graham",
    trending: false,
  },
  {
    id: 43,
    title: "Plant-Based Protein Swaps",
    image: "https://source.unsplash.com/800x600/?plant-based,protein",
    category: "Food",
    subcategory: "Diets",
    date: "March 14, 2025",
    summary: "How to replace meat with beans, lentils, and tofu.",
    content:
      "Chickpeas, black beans, and lentils can stand in for ground meat in tacos and chili. Tempeh and seitan offer texture for stir-fries, while pea-protein powders bolster smoothies.",
    featured: true,
    author: "Sophia Nguyen",
    trending: false,
  },
  {
    id: 44,
    title: "DIY Home Office Setup on a Budget",
    image: "https://source.unsplash.com/800x600/?home-office,budget",
    category: "Lifestyle",
    subcategory: "Home",
    date: "March 13, 2025",
    summary: "Ergonomic, functional, and budget-friendly solutions.",
    content:
      "Repurpose a sturdy table, add an adjustable chair, and use monitor risers made from books. Incorporate task lighting, cable management, and plants to boost mood and productivity.",
    featured: false,
    author: "Sofia Ramirez",
    trending: false,
  },
  {
    id: 45,
    title: "5 Mindfulness Apps Reviewed",
    image: "https://source.unsplash.com/800x600/?mindfulness,apps",
    category: "Health",
    subcategory: "Mental Health",
    date: "March 12, 2025",
    summary: "Which app helps you breathe, relax, and focus best?",
    content:
      "Headspace offers guided courses, Calm features nature soundscapes, and Waking Up dives into philosophy. Compare free tiers vs. subscriptions, and pick one you’ll use daily.",
    featured: false,
    author: "Zara Bennett",
    trending: false,
  },
  {
    id: 46,
    title: "Gadgets for Remote Work in 2025",
    image: "https://source.unsplash.com/800x600/?remote-work,gadget",
    category: "Technology",
    subcategory: "Gadgets",
    date: "March 11, 2025",
    summary: "Key hardware to stay productive at home.",
    content:
      "Noise-canceling headphones, ergonomic keyboards, high-resolution monitors, and portable webcams top the list. Don’t forget a reliable USB hub and fast SSD external drive for backups.",
    featured: true,
    author: "Lucas Brown",
    trending: false,
  },
  {
    id: 47,
    title: "Sustainable Fabrics in Fashion",
    image: "https://source.unsplash.com/800x600/?sustainable,fabric",
    category: "Fashion",
    subcategory: "Sustainable",
    date: "March 10, 2025",
    summary: "Recycled polyester, Tencel, and organic linen explained.",
    content:
      "Recycled polyester repurposes plastic waste; Tencel (lyocell) uses closed-loop processing; organic linen requires less water than cotton. Each offers distinct texture and environmental benefits.",
    featured: false,
    author: "Harper James",
    trending: false,
  },
  {
    id: 48,
    title: "Seasonal Soups for Spring",
    image: "https://source.unsplash.com/800x600/?spring,soup",
    category: "Food",
    subcategory: "Recipes",
    date: "March 9, 2025",
    summary: "Bright, fresh soups using spring produce.",
    content:
      "Make a chilled cucumber-dill soup, carrot-ginger bisque, or asparagus-pea velouté. Light broths and herb garnishes showcase produce at its peak.",
    featured: true,
    author: "Miguel Pereira",
    trending: false,
  },
  {
    id: 49,
    title: "Deep Work vs. Shallow Work",
    image: "https://source.unsplash.com/800x600/?deep-work,focus",
    category: "Lifestyle",
    subcategory: "Productivity",
    date: "March 8, 2025",
    summary: "Strategies to maximize focus and minimize distractions.",
    content:
      "Schedule uninterrupted blocks for cognitively demanding tasks, and batch shallow tasks like email into fixed slots. Use website blockers and set clear goals for each session.",
    featured: false,
    author: "Emma Brooks",
    trending: false,
  },
  {
    id: 50,
    title: "Advances in Remote Patient Monitoring",
    image: "https://source.unsplash.com/800x600/?remote,monitoring,healthcare",
    category: "Health",
    subcategory: "Medicine",
    date: "March 7, 2025",
    summary: "Wearables and telehealth devices that track vital signs at home.",
    content:
      "Bluetooth-enabled blood pressure cuffs, ECG patches, and glucometers sync to mobile apps, alerting clinicians to anomalies in real time. Early interventions reduce hospitalizations and improve chronic disease management.",
    featured: true,
    author: "Sophie Bennett",
    trending: false,
  },
];
export default posts;
